export const FETCH_CARD = 'FETCH_CARD';
export const FETCH_CARD_SUCCESS = 'FETCH_CARD_SUCCESS';
export const FETCH_CARD_FAILED = 'FETCH_CARD_FAILED';

export const CREATE_CARD = 'CREATE_CARD';
export const CREATE_CARD_SUCCESS = 'CREATE_CARD_SUCCESS';
export const CREATE_CARD_FAILED = 'CREATE_CARD_FAILED';

export const UPDATE_CARD = 'UPDATE_CARD';
export const UPDATE_CARD_SUCCESS = 'UPDATE_CARD_SUCCESS';
export const UPDATE_CARD_FAILED = 'UPDATE_CARD_FAILED';

export const DELETE_CARD = 'DELETE_CARD';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILED = 'DELETE_CARD_FAILED';

export const CARD_LISTENER = 'CARD_LISTENER';
export const CANCEL_CARD_LISTENER = 'CANCEL_CARD_LISTENER';
