export const FETCH_LIST = 'FETCH_LIST';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAILED = 'FETCH_LIST_FAILED';

export const CREATE_LIST = 'CREATE_LIST';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAILED = 'CREATE_LIST_FAILED';

export const UPDATE_LIST = 'UPDATE_LIST';
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS';
export const UPDATE_LIST_FAILED = 'UPDATE_LIST_FAILED';

export const DELETE_LIST = 'DELETE_LIST';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const DELETE_LIST_FAILED = 'DELETE_LIST_FAILED';

export const LIST_LISTENER = 'LIST_LISTENER';
export const CANCEL_LIST_LISTENER = 'CANCEL_LIST_LISTENER';
