export const UPLOAD = "UPLOAD_POST";
export const UPLOAD_SUCCESS = "UPLOAD_POST_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_POST_FAILURE";

export const FETCH_LIST = "FETCH_LIST_POST";
export const FETCH_LIST_SUCCESS = "FETCH_LIST_POST_SUCCESS";
export const FETCH_LIST_FAILURE = "FETCH_LIST_POST_FAILURE";

export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const LIKE_POST = "LIKE_POST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";

export const COMMENT_POST = "COMMENT_POST";
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS";
export const COMMENT_POST_FAILURE = "COMMENT_POST_FAILURE";