export const UPLOAD = "UPLOAD_POST";
export const UPLOAD_SUCCESS = "UPLOAD_POST_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_POST_FAILURE";

export const FETCH_LIST = "FETCH_LIST_POST";
export const FETCH_LIST_SUCCESS = "FETCH_LIST_POST_SUCCESS";
export const FETCH_LIST_FAILURE = "FETCH_LIST_POST_FAILURE";